[workspace]
authors = ["cyrus <cyrus28214@gmail.com>"]
channels = ["conda-forge"]
name = "Net-final"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10.13,<3.11"
pytorch-gpu = ">=1.11.0,<2"
torchvision = ">=0.12.0,<0.13"
pandas = ">=2.3.3,<3"
numpy = ">=1.26.4,<2"
scipy = ">=1.15.2,<2"
matplotlib = ">=3.9.1,<4"
